java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    aac:
      secrets:
        - name: aac-manage-case-s2s-secret
          alias: MANAGE_CASE_S2S_KEY
        - name: idam-mca-client-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-mca-system-user-username
          alias: IDAM_CAA_USERNAME
        - name: idam-mca-system-user-password
          alias: IDAM_CAA_PASSWORD
        - name: idam-noc-approver-username
          alias: IDAM_NOC_APPROVER_USERNAME
        - name: idam-noc-approver-password
          alias: IDAM_NOC_APPROVER_PASSWORD
        - name: notify-mca-api-key-secret
          alias: NOTIFY_MCA_API_KEY
  environment:
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api-pr-1260-java.ccd
    CCD_DEFINITION_STORE_API_BASE_URL: http://ccd-definition-store-api-pr-575-java.ccd
    ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-pr-929-java.am
    MANAGE_CASE_S2S_AUTHORISED_SERVICES: xui_webapp,ccd_data,finrem_case_orchestration,divorce_frontend,iac,nfdiv_cos,fpl_case_service,civil_service,prl_cos_api
