java:
  applicationPort: 4454
  image: 'hmctspublic.azurecr.io/aac/manage-case-assignment:latest'
  ingressHost: aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: aac
  autoscaling:
    enabled: false
    maxReplicas: 4
  keyVaults:
    aac:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: aac-manage-case-s2s-secret
          alias: MANAGE_CASE_S2S_KEY
        - name: idam-mca-client-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-mca-system-user-username
          alias: IDAM_CAA_USERNAME
        - name: idam-mca-system-user-password
          alias: IDAM_CAA_PASSWORD
        - name: idam-noc-approver-username
          alias: IDAM_NOC_APPROVER_USERNAME
        - name: idam-noc-approver-password
          alias: IDAM_NOC_APPROVER_PASSWORD
        - name: notify-mca-api-key-secret
          alias: NOTIFY_MCA_API_KEY
  environment:
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_OIDC_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    MCA_DS_PROXY_URLS_ALLOWED_LIST: /searchCases.*,/internal/searchCases.*,/internal/cases.*
    MCA_DEF_STORE_PROXY_URLS_ALLOWED_LIST: /api/display/challenge-questions.*
    MANAGE_CASE_S2S_AUTHORISED_SERVICES: xui_webapp,ccd_data,finrem_case_orchestration,divorce_frontend,iac,nfdiv_cos,fpl_case_service,prl_cos_api,et_cos,probate_backend,nfdiv_case_api
    CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCD_DEFINITION_STORE_API_BASE_URL: http://ccd-definition-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PRD_HOST: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

